### ISSUE TITLE
functions should also allow to return named list with atomics

### ISSUE THREAD

**Issue by QuayAu** [QuayAu/fxtract#16]

**Comment by QuayAu** [comment]
we need to check the batchtools results, if the functions return the right thing

**Comment by competulix** [comment]
![grafik](https://user-images.githubusercontent.com/8502704/51538027-73c4b900-1e50-11e9-9d37-e7f7fd29d122.png)

**Comment by QuayAu** [comment]
3593a2f27ec770e1110ee6ece066cd40541e8891
