### ISSUE TITLE
The vignette doesn't work.

### ISSUE THREAD

**Issue by JiaxiangBU** [QuayAu/fxtract#39]
See the screenshot.

![image](https://user-images.githubusercontent.com/15884785/53007440-387ad180-3472-11e9-9010-9fd257de2b9d.png)

https://cran.r-project.org/web/packages/fxtract/vignettes/fxtract.html

**Comment by QuayAu** [comment]
that's true, this will be fixed on the next update on CRAN.

However, the vignette will only contain a link to the online tutorial, which is available here:
https://quayau.github.io/fxtract/
