### ISSUE TITLE
make sliding window faster

### ISSUE THREAD

**Issue by QuayAu** [QuayAu/fxtract#8]
i just wrote a quick (and dirty) version of this function, which loops over the whole dataset.
@thullmann can you make this function faster?

**Comment by ja-thomas** [comment]
There is some discussion on what is already implemented in `data.table` and what is planned:

https://github.com/Rdatatable/data.table/issues/2778

**Comment by QuayAu** [comment]
I excluded this function for now. Maybe I'll add it again on a later version.
